{{- if not .Values.githubWebhookSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actions-metrics-converter.fullname" . }}
  labels:
    {{- include "actions-metrics-converter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.githubWebhookSecret.key }}: {{ required "githubWebhookSecret.value is required when githubWebhookSecret.existingSecret is not set" .Values.githubWebhookSecret.value | quote }}
{{- end }}
